### ISSUE TITLE
小数无效吗？都变成了0 

### ISSUE THREAD

**Issue by charrysong** [mrzhouxl/animated-number-vue3#1]

**Comment by charrysong** [comment]
![image](https://github.com/mrzhouxl/animated-number-vue3/assets/16949356/e1b6963a-54e0-48da-9d7a-647b6b151dbe)

**Comment by charrysong** [comment]
整数试了也是0

**Comment by charrysong** [comment]
![image](https://github.com/mrzhouxl/animated-number-vue3/assets/16949356/96adf490-fd2a-4528-8cdb-9e19f39d6151)

**Comment by mrzhouxl** [comment]
小数会取整，整数也不行，有demo吗

**Comment by mrzhouxl** [comment]
> ![image](https://user-images.githubusercontent.com/16949356/238123632-96adf490-fd2a-4528-8cdb-9e19f39d6151.png)

小数会取整，整数也不行吗？有demo吗
